version: "3.7"

services:
  python-codes:
    container_name: python-codes
    hostname: python-codes.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      python-codes-net:

networks:
  python-codes-net:
